name: New data contributor profile
description: Issue ticket for introducing oneself as a potential project contributor
title:  "{Your Name}: Data Contributor Profile"
labels: [ "data-nerds", "contributor profile"]
assignees:
  - paulvonderhaar
body:
  - type: textarea
    id: introduction
    attributes:
      label: Introduction
      description: Brief introduction of who you are and your interest in Open Austin
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: what-i-know
    attributes:
      label: What I know
      description: List in bullet point form your skills. This can include data analysis techniques, programming languages, machine learning methodologies, data visualization tools, and software used in data science workflows.
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: what-i-want-to-know
    attributes:
      label: What I want to know
      description: What are somethings you'd like to gain more experience with?
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: contact
    attributes:
      label: Contact info
      description: What's some contact info you are willing to share, such as email, in case someone wants to recruit you to an Open Austin project? (NOTE! this is a public)
      placeholder:
      value:
    validations:
      required: true
